# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4632547d57ce2c53ffb58343451d55c993c9c4290c1c7fc3909241b92df3610bdd778ffaec9b6a33fc13fc4115eb8bbe155b25f67b29b774392e0b31aa416583

test:
  secret_key_base: d4fb34d466a9790900c9f45cf47abea32ed0f1cb3b79a36c0b47117feb2d621d905827738526a2b600f1ba58bed1ae5399850b293b6aef70374e960647cf6bbd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
